# Generated by Django 3.1.3 on 2020-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
